version: "3.9"
name: enevold-prod

services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./backend
    env_file: [.env]
    environment:
      MONGO_URI: ${MONGO_URI}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mongo_data:
