version: "3.9"
name: enevold-dev

services:
  mongo:
    image: mongo:7
    container_name: enevold_mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    image: node:22-alpine
    container_name: enevold_web
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - mongo


volumes:
  mongo_data:
