version: "3.9"
name: enevold-dev

services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: enevold
    volumes: [mongo_data:/data/db]

  api:
    build: ./backend
    environment:
      MONGO_URI: mongodb://mongo:27017/enevold
      SPRING_PROFILES_ACTIVE: prod
    ports: ["8080:8080"]
    depends_on: [mongo]

  web:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api


volumes:
  mongo_data:
