server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: enevold
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/enevold},

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


app:
  # admin emails
  admin-emails: ${ADMIN_EMAILS:}
  # Allowed frontend origins for CORS
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8080}
  google:
    client-id: ${GOOGLE_CLIENT_ID}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.mongodb.driver: INFO
