server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: enevold
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/enevold}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
